import Header from '@/components/Header/Header'
// import styles from './global.css'
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Footer from '@/components/Footer/Footer'
import { lora, roboto } from './font'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${lora.variable} ${roboto.variable}`}>
      <body  className={`${lora.variable} ${roboto.variable}`}>
        <Header></Header>
        {children}
        <Footer></Footer>
        </body>
    </html>
  )
}
