import Header from "@/components/Header/Header";
// import styles from './global.css'
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Footer from "@/components/Footer/Footer";
import { lora, roboto } from "./font";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lora.variable} ${roboto.variable}`}>
        <AuthProvider>
          <Header></Header>
          {children}
          <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
